### ISSUE TITLE
graalvm-maven:latest-java17 not compatible with AWS Runtime

### ISSUE THREAD

**Issue by gquintana** [vegardit/docker-graalvm-maven#11]
There is a GLibC incompatibility
```
INIT_START Runtime Version: provided:al2.v20	Runtime Version ARN: arn:aws:lambda:eu-west-1::runtime:e448fca582d6ef7f5f1faf3cae4b2bb6521010ebae50e60019812234a4c0d549
./runner: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./runner)
./runner: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./runner)

```
graalvm-maven:22.3.2-java17 is OK

**Comment by sebthom** [comment]
I am not using AWS. What is your suggestion?

**Comment by gquintana** [comment]
No idea.
What's the difference between latest-java17 and 22.3.2-java17? Same Debian base image?

**Comment by sebthom** [comment]
`22.3.2-java17` is based on Debian Bullseye and GraalVM 22.3.2, whereas `latest-java17` / `17.0.8-java17` is based on Debian Bookworm and GraalVM 17.0.8.

Oracle changed the version scheme of GraalVM which means that 17.0.8 is a newer release than 22.3.2.
