### ISSUE TITLE
Support for Java 22

### ISSUE THREAD

**Issue by KafkaProServerless** [vegardit/docker-graalvm-maven#17]
Hello team,

This is my first ticket.
I have been using this project for long, really, just thank you.

Java 22 is around the corner.
Could you please support java 22 as well?

Thank you

**Comment by KafkaProServerless** [comment]
There is now, just released

**Comment by KafkaProServerless** [comment]
(to be precise, you commented arounf 9 hours ago time of this writing, and stable 22 got released 7 hours ago, time of this writing)

**Comment by KafkaProServerless** [comment]
![Screenshot 2024-03-20 203820](https://github.com/vegardit/docker-graalvm-maven/assets/44656335/48699c73-f04c-407a-bcd1-a4ca657f6fea)
![Screenshot 2024-03-20 200655](https://github.com/vegardit/docker-graalvm-maven/assets/44656335/a9f320a5-e3a7-4d3c-9dcc-c32e028de659)

**Comment by KafkaProServerless** [comment]
please @sebthom

**Comment by sebthom** [comment]
You'll have to wait a few days. I am away from computer atm.

**Comment by KafkaProServerless** [comment]
Thank you
