### ISSUE TITLE
crane fails because of missing auth in the container

### ISSUE THREAD

**Issue by eminaktas** [vegardit/docker-graalvm-maven#22]
Fails due to missing auth configuration to push the built images: https://github.com/vegardit/docker-graalvm-maven/actions/runs/10703183137

The error message:
```
Error: POST https://index.docker.io/v2/vegardit/graalvm-maven/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:vegardit/graalvm-maven Type:repository] map[Action:push Class: Name:vegardit/graalvm-maven Type:repository]]
```

@sebthom I saw the error. I will work on it to fix.

**Comment by sebthom** [comment]
The regular docker login happens here:

https://github.com/vegardit/docker-graalvm-maven/blob/6f8ff3fcfadf1a2cbe0c48c6b85407e40116cf78/.github/workflows/build.yml#L111-L115
